Output vhs/demo.gif

Set FontSize 16
Set Width 1200
Set Height 800

Set Shell zsh
Sleep 1s
Type "h5inspect dummy.h5"
Enter
Sleep 500ms
Down 2
Sleep 500ms
Down 1
Sleep 500ms
Down 1
Sleep 100ms
Down 1
Sleep 100ms
Down 1
Sleep 100ms
Down 1
Sleep 100ms
Down 1
Sleep 100ms
Ctrl+Z
Right
Escape
Type "[D"
Escape
Type "[A"
Escape
Type "[A"
Ctrl+Z
Right
Sleep 500ms
Escape
Type "[D"
Sleep 500ms
Type "/"
Sleep 500ms
Type "large"
Sleep 500ms
Escape
Down
Sleep 1s
Type "?"
Sleep 2.5s
